# Generated by Django 6.1.1 on 2026-09-11 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_date'], 'permissions': [('view_assigned_events_only', 'Can view only events they are personally assigned to (row-level restriction)')]},
        ),
    ]
