# Generated by Django 6.1.1 on 2026-09-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Cheque number, mobile money transaction ID, etc. — printed on the receipt as "Cash/Cheque No."', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='notes',
            field=models.CharField(blank=True, help_text='What this payment is for, e.g. "2 parasols 5x5" — printed on the receipt as "Being payment of".', max_length=255),
        ),
    ]
