# Generated by Django 6.1.1 on 2026-09-11 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_payment_reference_number_alter_payment_notes'),
        ('inventory', '0002_equipmentitem_default_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='equipment_item',
            field=models.ForeignKey(blank=True, help_text="Optional — link this line to an actual inventory item. Leave blank for services/fees (delivery, setup, etc.) that aren't physical equipment.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.equipmentitem'),
        ),
        migrations.AddField(
            model_name='quotationlineitem',
            name='equipment_item',
            field=models.ForeignKey(blank=True, help_text="Optional — link this line to an actual inventory item. Leave blank for services/fees (delivery, setup, etc.) that aren't physical equipment.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.equipmentitem'),
        ),
    ]
