# Generated by Django 6.1.1 on 2026-10-06 03:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_document_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileMoneyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=20)),
                ('transaction_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('payer_phone', models.CharField(blank=True, max_length=30)),
                ('payer_name', models.CharField(blank=True, max_length=150)),
                ('reference', models.CharField(blank=True, help_text='What the payer typed as the reason/reference.', max_length=255)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('matched', 'Recorded on invoice'), ('unmatched', 'Needs allocating'), ('ignored', 'Ignored')], default='unmatched', max_length=20)),
                ('raw', models.JSONField(blank=True, default=dict, help_text='The webhook body as received, for audit.')),
                ('allocated_by', models.ForeignKey(blank=True, help_text='Staff member who matched it to an invoice (blank when matched automatically).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_money_transaction', to='billing.payment')),
            ],
            options={
                'ordering': ['-received_at'],
                'unique_together': {('provider', 'transaction_id')},
            },
        ),
    ]
