# Generated by Django 6.1.1 on 2026-10-06 04:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_mobile_money_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='As printed on documents, e.g. "VAT".', max_length=60, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Percent added on top of the line items, e.g. 18 for 18%.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text="Inactive taxes can't be chosen on new documents.")),
                ('is_default', models.BooleanField(default=False, help_text='Pre-selected on new quotations. Only one tax can be the default.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='quotation',
            name='tax_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='quotation',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.taxgroup', verbose_name='Tax'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='tax_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.taxgroup', verbose_name='Tax'),
        ),
    ]
