# Generated by Django 6.1.1 on 2026-10-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_failedloginattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=150)),
                ('permission', models.CharField(blank=True, help_text="'app_label.codename', or blank for the role itself.", max_length=255)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('group_name', 'permission')},
            },
        ),
    ]
