# Generated by Django 6.1.1 on 2026-10-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_role_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyJobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
