# Generated by Django 6.1.1 on 2026-09-23 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Expense account these costs are booked to. Leave blank for General Expenses.', limit_choices_to={'account_type': 'expense', 'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_categories', to='accounting.account'),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='paid_from_account',
            field=models.ForeignKey(blank=True, help_text='Cash, mobile money or bank account the money came out of. Leave blank for Cash on Hand.', limit_choices_to={'detail_type': 'cash_bank', 'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account', verbose_name='Paid from'),
        ),
        migrations.AddField(
            model_name='incomerecord',
            name='deposit_account',
            field=models.ForeignKey(blank=True, help_text='Cash, mobile money or bank account the money went into. Invoice payments pick this from the payment method.', limit_choices_to={'detail_type': 'cash_bank', 'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account', verbose_name='Received into'),
        ),
        migrations.AddField(
            model_name='incomerecord',
            name='income_account',
            field=models.ForeignKey(blank=True, help_text='Leave blank for Other Income (or Event Services Income for invoice payments).', limit_choices_to={'account_type': 'income', 'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.account', verbose_name='Income account'),
        ),
    ]
