# Generated by Django 6.1.1 on 2026-09-23 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('finance', '0002_expensecategory_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenserecord',
            name='expense_account',
            field=models.ForeignKey(blank=True, help_text='General ledger account this cost is booked to. Filled in from the category; change it if needed.', limit_choices_to={'account_type': 'expense', 'is_active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_records', to='accounting.account', verbose_name='Expense account'),
        ),
    ]
