# Generated by Django 6.1.1 on 2026-10-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_expenserecord_expense_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomerecord',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Part of the amount that is tax collected for the government, not income (from taxed invoices).', max_digits=14),
        ),
    ]
