# Generated by Django 6.1.1 on 2026-09-11 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Equipment categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('unit', models.CharField(default='pieces', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.equipmentcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_issued', models.PositiveIntegerField()),
                ('issued_at', models.DateField()),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_issues', to='events.event')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_issued', to=settings.AUTH_USER_MODEL)),
                ('equipment_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='inventory.equipmentitem')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_returned', models.PositiveIntegerField()),
                ('returned_at', models.DateField()),
                ('condition_notes', models.CharField(blank=True, max_length=255)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='inventory.equipmentissue')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_returns_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-returned_at'],
            },
        ),
    ]
