# Generated by Django 6.1.1 on 2026-09-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitem',
            name='default_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Default rate per unit when quoting this item — pre-fills a quotation line, still editable per quote.', max_digits=14, null=True),
        ),
    ]
