# Generated by Django 6.1.1 on 2026-09-23 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0001_initial'),
        ('events', '0002_alter_event_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationlog',
            name='event',
            field=models.ForeignKey(blank=True, help_text='Optional: the event this contact was about.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_logs', to='events.event'),
        ),
    ]
