# Generated by Django 6.1.1 on 2026-09-23 20:45

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='e.g. 1000. Accounts sort by code.', max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income'), ('expense', 'Expense')], max_length=20)),
                ('detail_type', models.CharField(choices=[('cash_bank', 'Cash & bank'), ('current_asset', 'Current asset'), ('fixed_asset', 'Fixed asset'), ('other_asset', 'Other asset'), ('current_liability', 'Current liability'), ('long_term_liability', 'Long-term liability'), ('equity', 'Equity'), ('income', 'Operating income'), ('other_income', 'Other income'), ('cost_of_sales', 'Cost of sales'), ('expense', 'Operating expense'), ('other_expense', 'Other expense')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text="Inactive accounts keep their history but can't be used on new entries.")),
                ('system_key', models.CharField(blank=True, editable=False, help_text='Set on accounts the app posts to automatically; these can be renamed but not deleted or retyped.', max_length=40, null=True, unique=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Optional: show this account as a sub-account of another of the same type.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.account')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=20, unique=True)),
                ('date', models.DateField()),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, help_text='Receipt number, bank reference, etc.', max_length=60)),
                ('source', models.CharField(choices=[('manual', 'Manual journal'), ('opening', 'Opening balance'), ('transfer', 'Transfer'), ('income', 'Income record'), ('expense', 'Expense record')], default='manual', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries_created', to=settings.AUTH_USER_MODEL)),
                ('expense_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entry', to='finance.expenserecord')),
                ('income_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entry', to='finance.incomerecord')),
            ],
            options={
                'verbose_name_plural': 'journal entries',
                'ordering': ['-date', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='accounting.account')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry')),
            ],
            options={
                'ordering': ['pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('credit__gte', 0), ('debit__gte', 0), models.Q(models.Q(('credit', 0), ('debit__gt', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR')), name='journalline_one_positive_side')],
            },
        ),
    ]
