# Generated by Django 6.1.1 on 2026-10-06 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='reverses',
            field=models.OneToOneField(blank=True, help_text='The entry this one cancels out. Its created_by/created_at say who reversed it and when.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='accounting.journalentry'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual journal'), ('opening', 'Opening balance'), ('transfer', 'Transfer'), ('income', 'Income record'), ('expense', 'Expense record'), ('reversal', 'Reversal')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='PeriodClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closed_through', models.DateField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'get_latest_by': ['created_at', 'pk'],
            },
        ),
    ]
